version: '3.8'

services:
  graphs:
    image: graphs
    build: 
      context: ./
      dockerfile: ./code/Dockerfile
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - graphs-network
      
  postgres:
    image: postgres:14.1-alpine
    restart: always
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=trains
    volumes: 
      - db:/var/lib/postgresql/data
      - ./data:/etc/postgresql/data
      - ./data/trains.sql:/docker-entrypoint-initdb.d/trains.sql
    networks:
      - graphs-network

volumes:
  db:
    driver: local

networks:
  graphs-network:
    driver: bridge